---
new_page_extension: md
auto_deploy: false
admin_path: "/_admin"
webhook_url: 
sections:
- type: directory
  path: content/blog/frontend
  label: frontend
  create: documents
  match: "**/*"
  templates:
  - frontend-post
- type: directory
  path: content/blog/others
  label: others
  create: documents
  match: "**/*"
  templates:
  - others-posts
- type: directory
  path: content/blog/life
  label: life
  create: documents
  match: "**/*"
  templates:
  - life-posts
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: public
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
